In [1]:
import pandas as pd
import os

In [2]:
df_train = pd.read_csv('raw_data/raw_data_train.csv')
df_train.head()

,date,wind_speed_10m,temperature_2m,cloud_cover,relative_humidity_2m,surface_pressure,apparent_temperature,precipitation,vapour_pressure_deficit
0,2021-01-01 00:00:00+07:00,26.144030,19.50,100.0,70.98951,1020.28920,17.023354,0.0,0.657872
1,2021-01-01 01:00:00+07:00,24.192429,19.50,100.0,68.94631,1019.78986,17.147188,0.0,0.704225
2,2021-01-01 02:00:00+07:00,23.565569,19.35,99.0,67.36236,1019.09000,16.914827,0.0,0.733305
3,2021-01-01 03:00:00+07:00,24.192429,19.20,91.0,68.21654,1018.59010,16.690643,0.0,0.707482
4,2021-01-01 04:00:00+07:00,23.838959,19.25,100.0,66.90323,1018.89010,16.706848,0.0,0.739021

In [3]:
df_test = pd.read_csv('raw_data/raw_data_test.csv')
df_test.head()

,date,wind_speed_10m,temperature_2m,cloud_cover,relative_humidity_2m,surface_pressure,apparent_temperature,precipitation,vapour_pressure_deficit
0,2025-11-09 21:00:00+07:00,5.411986,26.25,100.0,89.580230,1010.33110,31.812645,0.0,0.355126
1,2025-11-09 22:00:00+07:00,3.864764,26.00,100.0,90.914170,1010.23035,31.788673,0.0,0.305128
2,2025-11-09 23:00:00+07:00,2.099143,25.35,98.0,94.488280,1009.72810,31.397144,0.0,0.178110
3,2025-11-10 00:00:00+07:00,2.099143,25.15,100.0,95.048485,1009.52770,31.134106,0.0,0.158120
4,2025-11-10 01:00:00+07:00,1.018234,25.05,100.0,96.479480,1008.92786,31.287022,0.0,0.111755

In [4]:
print(df_train.dtypes, df_test.dtypes, sep='\n')

date                           str
wind_speed_10m             float64
temperature_2m             float64
cloud_cover                float64
relative_humidity_2m       float64
surface_pressure           float64
apparent_temperature       float64
precipitation              float64
vapour_pressure_deficit    float64
dtype: object
date                           str
wind_speed_10m             float64
temperature_2m             float64
cloud_cover                float64
relative_humidity_2m       float64
surface_pressure           float64
apparent_temperature       float64
precipitation              float64
vapour_pressure_deficit    float64
dtype: object

In [5]:
output_dir = "clean_data"
os.makedirs(output_dir, exist_ok=True)

# Chuyển đổi cột thời gian
df_train['date'] = pd.to_datetime(df_train['date']).dt.tz_localize(None)
df_test['date'] = pd.to_datetime(df_test['date']).dt.tz_localize(None)
df_train = df_train.rename(columns={'date': 'time'})
df_test = df_test.rename(columns={'date': 'time'})

#Xóa trùng lặp
df_train = df_train.drop_duplicates(subset=['time'])
df_test = df_test.drop_duplicates(subset=['time'])

# Sắp xếp lại thời gian
df_train = df_train.sort_values(by='time').reset_index(drop=True)
df_test = df_test.sort_values(by='time').reset_index(drop=True)

# Đưa cột 'time' làm Index để ép tần suất thời gian liên tục từng giờ (.asfreq('H'))
# Nếu có giờ nào bị khuyết dữ liệu, Pandas sẽ tự động chèn thêm 1 dòng trống (NaN)
# Cuối cùng, dùng .reset_index() để trả cột 'time' về làm một cột bình thường 
df_train = df_train.set_index('time').asfreq('h').reset_index()
df_test = df_test.set_index('time').asfreq('h').reset_index()

train_path = os.path.join(output_dir, "clean_data_train.csv")
test_path = os.path.join(output_dir, "clean_data_test.csv")

df_train.to_csv(train_path, index=False, encoding="utf-8-sig")
df_test.to_csv(test_path, index=False, encoding="utf-8-sig")

print(f" - Train: {len(df_train)} dòng (Lưu tại {train_path})")
print(f" - Test:  {len(df_test)} dòng (Lưu tại {test_path})")

 - Train: 42573 dòng (Lưu tại clean_data\clean_data_train.csv)
 - Test:  4731 dòng (Lưu tại clean_data\clean_data_test.csv)