In [11]:
import pandas as pd
import os

In [12]:
df_train = pd.read_csv('raw_data/raw_data_train.csv')
df_train.head()

,date,wind_speed_10m,temperature_2m,cloud_cover,relative_humidity_2m,surface_pressure,apparent_temperature,precipitation,vapour_pressure_deficit
0,2021-01-01 00:00:00+07:00,26.144030,19.50,100.0,70.98951,1020.28920,17.023354,0.0,0.657872
1,2021-01-01 01:00:00+07:00,24.192429,19.50,100.0,68.94631,1019.78986,17.147188,0.0,0.704225
2,2021-01-01 02:00:00+07:00,23.565569,19.35,99.0,67.36236,1019.09000,16.914827,0.0,0.733305
3,2021-01-01 03:00:00+07:00,24.192429,19.20,91.0,68.21654,1018.59010,16.690643,0.0,0.707482
4,2021-01-01 04:00:00+07:00,23.838959,19.25,100.0,66.90323,1018.89010,16.706848,0.0,0.739021

In [13]:
df_test = pd.read_csv('raw_data/raw_data_test.csv')
df_test.head()

,date,wind_speed_10m,temperature_2m,cloud_cover,relative_humidity_2m,surface_pressure,apparent_temperature,precipitation,vapour_pressure_deficit
0,2026-05-19 00:00:00+07:00,7.695920,28.00,90.0,85.04454,1005.74445,33.778435,0.0,0.564673
1,2026-05-19 01:00:00+07:00,8.171683,27.75,97.0,83.51010,1004.44476,33.099693,0.0,0.613646
2,2026-05-19 02:00:00+07:00,7.814986,27.40,98.0,85.49241,1004.14400,32.834595,0.0,0.528956
3,2026-05-19 03:00:00+07:00,8.557102,27.10,97.0,85.97543,1003.34360,32.298230,0.0,0.502458
4,2026-05-19 04:00:00+07:00,8.731392,27.00,98.0,85.70878,1003.44293,32.077366,0.0,0.509028

In [14]:
print(df_train.dtypes, df_test.dtypes, sep='\n')

date                           str
wind_speed_10m             float64
temperature_2m             float64
cloud_cover                float64
relative_humidity_2m       float64
surface_pressure           float64
apparent_temperature       float64
precipitation              float64
vapour_pressure_deficit    float64
dtype: object
date                           str
wind_speed_10m             float64
temperature_2m             float64
cloud_cover                float64
relative_humidity_2m       float64
surface_pressure           float64
apparent_temperature       float64
precipitation              float64
vapour_pressure_deficit    float64
dtype: object

In [15]:
output_dir = "clean_data"
os.makedirs(output_dir, exist_ok=True)

# Chuyển đổi cột thời gian
df_train['date'] = pd.to_datetime(df_train['date']).dt.tz_localize(None)
df_test['date'] = pd.to_datetime(df_test['date']).dt.tz_localize(None)
df_train = df_train.rename(columns={'date': 'time'})
df_test = df_test.rename(columns={'date': 'time'})

# Sắp xếp lại thời gian
df_train = df_train.sort_values(by='time').reset_index(drop=True)
df_test = df_test.sort_values(by='time').reset_index(drop=True)

train_path = os.path.join(output_dir, "clean_data_train.csv")
test_path = os.path.join(output_dir, "clean_data_test.csv")

df_train.to_csv(train_path, index=False, encoding="utf-8-sig")
df_test.to_csv(test_path, index=False, encoding="utf-8-sig")

print(f" - Train: {len(df_train)} dòng (Lưu tại {train_path})")
print(f" - Test:  {len(df_test)} dòng (Lưu tại {test_path})")

 - Train: 47136 dòng (Lưu tại clean_data\clean_data_train.csv)
 - Test:  168 dòng (Lưu tại clean_data\clean_data_test.csv)